### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by xAcrosonicx** [shupershuff/PalworldServerTools#1]
Hello,

I am not seeing a discussion tab so figured I would drop it here. First of all, thank you so much for posting this - I am excited to dig in! A few things to note:

1. I have noticed a lot of users (including myself) are running it via the Steam Dedicated Server option, rather than SteamCMD. Would it be possible to add an option in the config to disable everything SteamCMD related and use the dedicated server option? Most who use this option have a start.bat (or similar) to launch the server.

2. I, along with some others on reddit, are very interested in the HomeAssistant setup part you mentioned. If/when you are able to get around to documenting that we would greatly appreciate it!

**Comment by Mesquitadex** [comment]
Could someone help me and mine just looks like this: [29/01/24 08:59:19] [INFO]    - Initialisation: Script Started.
[29/01/24 08:59:19] [INFO]    - Initialisation: Attempting to import config.xml
[29/01/24 08:59:19] [INFO]    - Initialisation: Config imported successfully.
[29/01/24 08:59:19] [INFO]    - Initialisation: Checking if ARRCON.exe can be found.
[29/01/24 08:59:19] [SUCCESS] - Initialisation: ARRCON was found in the specified path.
[29/01/24 08:59:19] [INFO]    - Initialisation: Launch parameter  provided.

**Comment by shupershuff** [comment]
> 1. I have noticed a lot of users (including myself) are running it via the Steam Dedicated Server option, rather than SteamCMD. Would it be possible to add an option in the config to disable everything SteamCMD related and use the dedicated server option? Most who use this option have a start.bat (or similar) to launch the server.


Yes I will look into this. Please note that looking at [Steam's parameter options](https://developer.valvesoftware.com/wiki/Command_line_options#Steam) and [these other options](https://gist.github.com/davispuh/6600880) which apparently work, it's unclear if it's possible to force an update the server software when a new release is out so I can't promise any smarts around ensuring it's up to date at launch.

> 2. I, along with some others on reddit, are very interested in the HomeAssistant setup part you mentioned. If/when you are able to get around to documenting that we would greatly appreciate it!
I will get onto that as soon as I can :)

**Comment by shupershuff** [comment]
> 2. I, along with some others on reddit, are very interested in the HomeAssistant setup part you mentioned. If/when you are able to get around to documenting that we would greatly appreciate it!

See [PalworldServerTools Home Assistant Documentation](https://github.com/shupershuff/PalworldServerTools/blob/main/docs/HOMEASSISTANT.md). Let me know if that page needs any clarification or more info.

**Comment by shupershuff** [comment]
> Hello,
> 
> I am not seeing a discussion tab so figured I would drop it here. First of all, thank you so much for posting this - I am excited to dig in! A few things to note:

Yea so I didn't know Discussions was a thing haha. Have since enabled it on the repo:
https://github.com/shupershuff/PalworldServerTools/discussions

**Comment by shupershuff** [comment]
> 1. I have noticed a lot of users (including myself) are running it via the Steam Dedicated Server option, rather than SteamCMD. Would it be possible to add an option in the config to disable everything SteamCMD related and use the dedicated server option? Most who use this option have a start.bat (or similar) to launch the server.

Unfortunately it's not possible to update the game without SteamCMD as there are no arguments that can be sent to steam.exe to force an update of an app.
I'll make it so the script allows you to run it without steamcmd being installed, however you will not have the ability to update the server, this will need to be done manually. I would recommend using steamcmd as it was designed for this sort of thing.

**Comment by shupershuff** [comment]
I've made it so that even if players have installed via the normal steam client, it can still be updated using SteamCMD. SteamCMD will auto install if not found.
