### ISSUE TITLE
I know you're working on backup stuff for a future release...

### ISSUE THREAD

**Issue by jonathanweinberg** [shupershuff/PalworldServerTools#4]
Thought I'd dump some info I found out about backups for Palworld here. Also, if / when you start working on it, any chance you want to add a branch to work on it with you?

https://github.com/xNul/palworld-host-save-fix

https://steamcommunity.com/app/1623730/discussions/0/4132683013928292938/?l=japanese&ctp=2#c4139439021818210947

Have a great day!

**Comment by shupershuff** [comment]
Hi there, thanks for the question.
I've built the backup functionality and it will be in the next release. Note that the backup feature is purely to make copies of player and world data so you've got versions you can fall back too.

Please note that the links you've posted here aren't backup related but are about how to resolve GUID mismatches between world data and player data. Both data sets are relational and as such are quite fragile if ID's don't match between the files.
I don't intend to add in functionality for resolving GUID/ID issues as firstly it's not an issue that should occur with normal use going forward and secondly other folk have already done fine work on relatively complicated converters used to deserialise and decompress the .sav data and convert it back.

All that said, happy to collaborate on any feature/improvement, still a bit new to Github so haven't figured out the whole branch/PR thing yet.

**Comment by shupershuff** [comment]
I've added a backup feature as part of 1.1.0
