### ISSUE TITLE
ARRCON is working fine but not using the script.

### ISSUE THREAD

**Issue by jjom0** [shupershuff/PalworldServerTools#5]
Great work you've done here!
But I'm wondering what could be the issue here as the server is Offline using the ps1 script via PowerShell (even on elevated).
![image](https://github.com/shupershuff/PalworldServerTools/assets/159172916/0163a08a-3769-428e-8c50-cf1e334c07c9)

But I can communicate well with my server using the stand-alone ARRCON.
![image](https://github.com/shupershuff/PalworldServerTools/assets/159172916/e12e7e94-82c4-4e7c-a198-83ca4302d04d)

Here's the configuration file.
![image](https://github.com/shupershuff/PalworldServerTools/assets/159172916/e5bb9413-9169-4104-821a-90c80e2318ee)

**Comment by shupershuff** [comment]
I should have a new release out tonight which should resolve this.

**Comment by shupershuff** [comment]
Please test with the latest release. If you still have issues let me know and I can help troubleshoot.

**Comment by jjom0** [comment]
Thanks, but the issue still persists. 
My ARRCON commands on the CMD works just fine, however, there's always a case of closing connection for like every 30 seconds to 1 minute. 
![image](https://github.com/shupershuff/PalworldServerTools/assets/159172916/54149b15-cbf1-4ef2-b422-0a995b78e663)
I never had a connection that lasts for a minute or two.

I've also tried to use a NuGet RCON for csharp/.net to create my RCON but with the same result of Connection is closed.
PORT : 25575

**Comment by shupershuff** [comment]
Are you running the script on the same host that the server is running on?
