### ISSUE TITLE
Running with -setup tells me to run with -setup

### ISSUE THREAD

**Issue by theletterV42** [shupershuff/PalworldServerTools#6]
"If the server files don't exist yet, then please run the -setup parameter."

But I'm already running with the -setup parameter.

Workaround: changed "true" to "false" on line 1301.

**Comment by shupershuff** [comment]
Hmm. Was server path specified in config.xml?

**Comment by theletterV42** [comment]
<ServerPath>D:\pal.server\server</ServerPath>

Directory exists but is empty.

**Comment by shupershuff** [comment]
Oh after rereading my code your workaround is actually the fix due to a mistake on my part. It's supposed to be $setup -ne $True

**Comment by shupershuff** [comment]
Resolved in v1.1.1
